#!/bin/bash

if [ $# -ne 2 ] ; then
  echo "Usage: ssh-add-pass keyfile passfile"
  exit 1
fi

_MY_PASSPHRASE_=$2

expect << EOF
  spawn ssh-add $1
  expect "Enter passphrase"
  send "${_MY_PASSPHRASE_}\r"
  expect eof
EOF
