serve:
    bot_token: YOUR_BOT_TOKEN__REQUIRED
    admin_ids: ADMIN_TELEGRAM_IDS_SEPARATED_BY_COMMAS_WITHOUT_SPACE
    moderator_ids: MODERATOR_TELEGRAM_IDS_SEPARATED_BY_COMMAS_WITHOUT_SPACE
    user_ids: USER_TELEGRAM_IDS_SEPARATED_BY_COMMAS_WITHOUT_SPACE
    # default_model_manager: MODEL_MANAGER_TO_USER_BY_DEFAULT__CAN_BE_EMPTY_OR_FOR_EXAMPLE_ollama
    # default_model: MODEL_MANAGER_TO_USER_BY_DEFAULT__CAN_BE_EMPTY_OR_FOR_EXAMPLE_llama3:latest
    db_protocol: YOUR_DATABASE_HOST__postgresql+asyncpg_BY_DEFAULT
    db_host: YOUR_DATABASE_HOST__0.0.0.0_BY_DEFAULT
    db_name: YOUR_DATABASE_NAME__quackamollie_BY_DEFAULT
    db_username: YOUR_DATABASE_USER
    db_password: YOUR_DATABASE_PASSWORD
    db_port: YOUR_DATABASE_PORT
    db_url: DIRECTLY_OVERRIDE_THE_WHOLE_DATABASE_URL_IF_NEEDED
db:
    db_protocol: YOUR_DATABASE_HOST__postgresql+asyncpg_BY_DEFAULT
    db_host: YOUR_DATABASE_HOST__0.0.0.0_BY_DEFAULT
    db_name: YOUR_DATABASE_NAME__quackamollie_BY_DEFAULT
    db_username: YOUR_DATABASE_USER
    db_password: YOUR_DATABASE_PASSWORD
    db_port: YOUR_DATABASE_PORT
    db_url: DIRECTLY_OVERRIDE_THE_WHOLE_DATABASE_URL_IF_NEEDED
